"""
Exploration script for unexpected curves on Z_n = (n-th roots of unity on the
conic uv=w^2) union {center point [0:0:1]}, for n = 2r even.

For each r we:
  1. Build I_{Z'} = (Q, G) with Q = uv - w^2, G = v^r - u^r  (complete intersection,
     n = 2r points on the conic).
  2. Build [I_Z]_d = { F in [I_{Z'}]_d : F(0,0,1) = 0 }  (impose vanishing at center).
  3. For multiplicity mu=2 unexpected curves: build the 3 x k matrix of
     (f(s,t), f_u(s,t), f_v(s,t)) for a basis f_1..f_k of the affine dehomogenization
     of [I_Z]_d, and check whether all 3x3 minors vanish identically in (s,t).
     If dim < 3 use the full available minors (min(3,k) x min(3,k)).
  4. Report dim[I_Z]_d and whether it's "unexpected" (generic rank < min(3,k)).
"""
import itertools
import sympy as sp

u, v, w, s, t = sp.symbols('u v w s t')


def monomials(vars_, d):
    n = len(vars_)
    out = []
    for exps in itertools.combinations_with_replacement(range(n), d):
        term = sp.Integer(1)
        for i in exps:
            term *= vars_[i]
        out.append(sp.expand(term))
    return out


def poly_to_vec(poly, mono_basis):
    poly = sp.expand(poly)
    return [poly.coeff(m) if False else None for m in mono_basis]  # placeholder, unused


def coeff_vector(poly, mono_list):
    """Return coefficient vector of poly (homogeneous degree d in u,v,w) w.r.t. mono_list."""
    poly = sp.Poly(sp.expand(poly), u, v, w)
    vec = []
    for m in mono_list:
        mp = sp.Poly(m, u, v, w)
        (exps,) = mp.monoms()
        c = poly.coeff_monomial(u**exps[0] * v**exps[1] * w**exps[2])
        vec.append(c)
    return vec


def space_from_generators(gens, d, deg_gens):
    """gens: list of (poly, degree). Returns list of basis polys spanning [ideal]_d
    generated by multiplying each gen by all monomials to reach degree d, then
    row-reduce coefficient vectors w.r.t. degree-d monomial basis."""
    mono_d = monomials((u, v, w), d)
    rows = []
    polys = []
    for g, dg in zip(gens, deg_gens):
        if d - dg < 0:
            continue
        for m in monomials((u, v, w), d - dg):
            p = sp.expand(g * m)
            polys.append(p)
            rows.append(coeff_vector(p, mono_d))
    if not rows:
        return [], mono_d
    M = sp.Matrix(rows)
    # row reduce to find a basis (rref on rows, then reconstruct polys from rref rows)
    rref, pivots = M.T.rref()  # transpose trick: columns become rows for rank/basis extraction
    # Actually just use M itself: find a maximal independent subset of rows.
    _, pivot_cols = M.rref()
    # Use column-space approach on M^T to get independent rows of M:
    Mt = M.T
    rref_t, pivots_t = Mt.rref()
    basis_polys = [polys[i] for i in pivots_t]
    return basis_polys, mono_d


def dim_IZprime_d(r, d):
    Q = u * v - w**2
    G = v**r - u**r
    basis_polys, mono_d = space_from_generators([Q, G], d, [2, r])
    return basis_polys, mono_d


def dim_IZ_d(r, d):
    """Impose F(0,0,1)=0, i.e. coefficient of w^d must vanish."""
    basis_polys, mono_d = dim_IZprime_d(r, d)
    if not basis_polys:
        return []
    mono_d_local = monomials((u, v, w), d)
    vecs = [coeff_vector(p, mono_d_local) for p in basis_polys]
    M = sp.Matrix(vecs)  # rows = basis polys, cols = monomials
    # find index of w^d in mono_d_local
    wd_index = None
    for idx, m in enumerate(mono_d_local):
        mp = sp.Poly(m, u, v, w)
        (exps,) = mp.monoms()
        if exps == (0, 0, d):
            wd_index = idx
            break
    col = M[:, wd_index]
    # Kernel of the linear functional "evaluate coeff of w^d" acting on row space.
    # We want combinations c such that (c^T M)[wd_index] = 0, i.e. c . col = 0.
    if col.is_zero_matrix:
        return basis_polys  # functional is zero on whole space -> all of I_{Z'}_d satisfies it
    ns = col.T.nullspace()  # null space of row vector (1 x k) acting on the left
    result = []
    for vec in ns:
        combo = sum(sp.nsimplify(vec[i]) * basis_polys[i] for i in range(len(basis_polys)))
        result.append(sp.expand(combo))
    return result


def jet_conditions(mu):
    """Return list of (dx,dy) partial derivative orders (a,b) with a+b < mu,
    giving binom(mu+1,2) conditions for multiplicity mu at a point."""
    conds = []
    for total in range(mu):
        for a in range(total + 1):
            b = total - a
            conds.append((a, b))
    return conds


def check_unexpected(r, d, mu, verbose=True):
    IZ_basis = dim_IZ_d(r, d)
    k = len(IZ_basis)
    ncond = mu * (mu + 1) // 2
    if verbose:
        print(f"r={r} (n={2*r}), d={d}, mu={mu}: dim [I_Z]_d = {k}, #conditions={ncond}")
    if k == 0:
        return k, False
    fs = [sp.expand(F.subs(w, 1)) for F in IZ_basis]
    conds = jet_conditions(mu)
    rows = []
    for (a, b) in conds:
        row = []
        for f in fs:
            df = f
            for _ in range(a):
                df = sp.diff(df, u)
            for _ in range(b):
                df = sp.diff(df, v)
            row.append(sp.expand(df.subs({u: s, v: t})))
        rows.append(row)
    M = sp.Matrix(rows)  # ncond x k
    target_rank = min(ncond, k)
    found_nonzero_minor = False
    for cols in itertools.combinations(range(k), target_rank):
        submat = M[list(range(target_rank)), list(cols)]
        det = sp.expand(submat.det())
        if det != 0:
            found_nonzero_minor = True
            break
    unexpected = not found_nonzero_minor
    if verbose:
        print(f"   generic rank = {'full (' + str(target_rank) + ')' if found_nonzero_minor else '< ' + str(target_rank)}  => {'UNEXPECTED' if unexpected else 'expected'}")
    return k, unexpected


if __name__ == '__main__':
    for mu in (2, 3):
        for r in range(2, 6):
            n = 2 * r
            print(f"=== mu={mu}, n={n} (r={r}) ===")
            for d in range(1, r + 4):
                check_unexpected(r, d, mu)
            print()
